### PR TITLE
Add filter icon

### PR DESCRIPTION
**Pull request by LanesGood**
Two options here: straight corners, or slightly rounded and outlined. At small sizes, I find the outline appears a little more readable as a filter, but want a second opinion. I think only one should be merged in. 

image

### CODE REVIEW

**Comment by ricardoduplos** [comment]
@LanesGood I prefer the straight corners one. I have made a few tweaks. Let me know what you think.

**Comment by LanesGood** [comment]
@ricardoduplos thanks for the edits - I think the additional squaring off of the top looks great! I bumped the version and recompiled the font - making this PR ready for review.

**Comment by LanesGood** [comment]
@ricardoduplos @danielfdsilva we've been using this icon - can I merge?

**Review by danielfdsilva — APPROVED** [review]
:shipit:

**Pull request merged**
